##################################################################################
## Service
##################################################################################

mode = ""

##################################################################################
[connecting]
##################################################################################
#
# The name of the service. These must be unique across all connected services
name = "c4"
#
# Aliases of the service. These must be unique across all connected services
aliases = [""]
#
# Arguments that will be sent to the service at runtime if it is being managed
# by the process launcher
args = []
#
# Environment variables that will be set before launching the service if it is
# being managed by the process launcher
env = []
#
# The language(python|go|node) the service is written in. 
language = "go"
#
# If a bin path is supplied it will be used to launch the service if it is being 
# managed by the process launcher
bin_path = "./c4"
#
# If a src path is supplied it will be used to build the service if it is being 
# managed by the process launcher
# NOTE: For Go projects -- Specify a path that will be able to be started using
#       *.go (with *_test.go filtered out)
src_path = ""
#

##################################################################################
[management]
##################################################################################


